

server:
  servlet:
    session:
      timeout: 60
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: root
  main:
    # Spring Boot 2.1 需要显式开启bean override
    allow-bean-definition-overriding: true
  redis:
    host: 129.28.180.71
    port: 6379
  session:
    store-type: redis
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/